### ISSUE TITLE
IPTV Merge 'un-associates" guide data 

### ISSUE THREAD

**Issue by markosjal** [matthuisman/slyguy.addons#330] opened 2023-01-07 21:49 UTC
I have a video source by way of a plugin and a guide source. If I load the two into PVR IPTV Simple  they work fine

The addon/plugin is USTVGO. It allows the output of a m3u file

The guide data from https://raw.githubusercontent.com/interlark/ustvgo-tvguide/master/ustvgo.for-dark-bg.xml

they work fine together loaded into PVR IPTV Simple on Kodi

Upon merging with other sources using IPTV Merge however I seem to loose the guide data/channel associations for that one source

I have disabled the proxy settings, but also tested with it enabled. 

What to try?
  
I would rather not publicly upload the outputted files but can do so if there is a private method.

**Comment by matthuisman** [comment] 2023-01-07 22:25
M3u8 would help.  Even just a single channel. Remove the url if needed

**Comment by matthuisman** [comment] 2023-01-07 22:45
try [v0.22.9](https://github.com/matthuisman/slyguy.addons/commit/8048d116fa7f716e84a8b198adf46e1102315cf5) and see if that fixes the issue :)

**Comment by markosjal** [comment] 2023-01-07 23:48
I am already on that latest version. BTW I never had this issue before on x86-64 Libreelec this is android

`to merge

#EXTINF:-1 tvg-id="9233011874" tvg-name="ABC" tvg-logo="https://raw.githubusercontent.com/Theitfixer85/myepg/master/Logos/abc-us.png" group-title="USTVGO",ABC
plugin://plugin.video.ustvgo/?action=play&video=ABC


merge out

#EXTINF:-1 group-title="USTVGO" tvg-chno="1" tvg-id="9233011874" tvg-logo="https://raw.githubusercontent.com/Theitfixer85/myepg/master/Logos/abc-us.png" tvg-name="ABC",ABC
plugin://plugin.video.ustvgo/?action=play&video=ABC`

**Comment by matthuisman** [comment] 2023-01-07 23:50
I only just pushed that new version. Please try it

**Comment by markosjal** [comment] 2023-01-07 23:53
yes it show as as most recently updated addon

**Comment by matthuisman** [comment] 2023-01-07 23:55
Yes, tvg-id is used to match in epg or fallback to name matching. 

So it should match ABC on its name

**Comment by markosjal** [comment] 2023-01-08 01:22
Data cleared now its all blank. Finding it very temperamental and unreliable on Android , although it seemed to work 100% on libreelec Generic x86-64 using much of the same playlists and guide data.

**Comment by matthuisman** [comment] 2023-01-08 01:28
And if you set iptv simple directly to the urls on Android, it works 100%?

**Comment by matthuisman** [comment] 2023-01-08 07:38
Oh, I think I know what the problem is.

Go into IPTV Merge settings > General > and make sure "Remove EPG Orphans" is disabled.
If thats enabled - I think that will stop the XML elements being merged across :)

**Comment by markosjal** [comment] 2023-01-08 09:49
Yes as I initially tested my hand made playlist with its embedded EPG and it was fine 

Now I have lost ALL PVR IPTV Simple guide data on all three systems 

Now getting error on android "error starting SlyGuy Common Service..."

Much seems to have gone to hell since then

I would have been better off ignoring my android problems. Nothing works now in terms of guide data

**Comment by markosjal** [comment] 2023-01-08 09:57
Just confirming 

On Android at first I was able to load my playlist with embedded guide URLS and it was working

Now I seem to have completely lost that functionality at least on Android

**Comment by markosjal** [comment] 2023-01-08 10:05
I would like to privately send you a link to previously working m3u link that no longer works , but do not want to post it publicly 

It does not look like I can PM you here on github

**Comment by matthuisman** [comment] 2023-01-08 10:16
If it's now not working directly in iptv simple, then that's out of my
control sorry

**Comment by markosjal** [comment] 2023-01-08 10:40
I first want to point out that this guide data is NOT in and NEVER HAS BEEN entered into EPG of IPTVMerge as it has always worked embedded in the m3u file as
`x-tvg-url="https://iptv-org.github.io/epg/guides/ie.xml,https://iptv-org.github.io/epg/guides/uk.xml,https://iptv-org.github.io/epg/guides/us.xml,https://i.mjh.nz/au/Sydney/epg.xml,https://iptv-org.github.io/epg/guides/ca.xml,https://iptv-org.github.io/epg/guides/it.xml"`

Now it seems IPTV Merge no longer supports that as all of that guide data is GONE 

I THOUGHT PVR IPTV Simple also supported it but I may have been mistaken but d not believe so

So the question remains  Should IPTV Merge support x-tvg-url, and if so, why is it suddenly failing?

**Comment by markosjal** [comment] 2023-01-08 20:26
I have now confirmed: I can load multiple M3u files and EPGs adding each m3u and EPG separately.  As soon as I add a m3u file with x-tvg-url it breaks the entire guide where it worked before (Even prevents standard EPG guide data from loading) . Not sure why or what the difference is . but if I get more time I have one libreelec x86-64 machine that has an older version of IPTV Merge (22.6?) that I can play with later and see if this happened as a result of one of the recent updates, or if it some other weirdness. I have been happily using m3u file with x-tvg-url with IPTV Merge for many months and it surprises me that it seems to have now failed

**Comment by matthuisman** [comment] 2023-01-08 21:45
can you poste the entire first line of your m3u8 so I can test :)

I think it may have been a recent update to how I parse attribs that broke it

**Comment by markosjal** [comment] 2023-01-08 23:51
`#EXTM3U x-tvg-url="https://iptv-org.github.io/epg/guides/ie.xml,https://iptv-org.github.io/epg/guides/uk.xml,https://iptv-org.github.io/epg/guides/us.xml,https://i.mjh.nz/au/Sydney/epg.xml"`

**Comment by matthuisman** [comment] 2023-01-09 00:24
perfect. final test - if using a single xml URL - does it work?

**Comment by matthuisman** [comment] 2023-01-09 01:09
looking at my parsing code, the above EXTM3U line is parsed correctly.

So, it might be at the stage where you send me your M3U8 so I can test.
email to: blog@matthuisman.nz

**Comment by matthuisman** [comment] 2023-01-09 05:31
Actually,  this might be due to the missing channel name for one of the channels in the Australian epg. That should be fixed soon.

**Comment by matthuisman** [comment] 2023-01-09 05:43
Might not be fixed until tomorrow.  In the meantime, try removing the au epg url and see if it then works

**Comment by matthuisman** [comment] 2023-01-09 07:40
ok AU epgs should now be fixed. pretty sure this will solve your issue.

**Comment by markosjal** [comment] 2023-01-10 01:17
I see version now has gone from xx.0 to xx.1 and it was first noted and working as of 13 hours ago here as of this posting

**Comment by matthuisman** [comment] 2023-01-10 01:18
Iptv merge update was not for this fix. The problem all along was the australia had a bad epg

**Closed by matthuisman** 2023-01-10 01:18 UTC
