### ISSUE TITLE
Disney+ addon language settings

### ISSUE THREAD

**Issue by kevwag** [matthuisman/slyguy.addons#103] opened 2021-12-11 00:47 UTC
In the Disney+ addon, the settings pages in the current version differ substantially from the ones documented on https://www.matthuisman.nz/2020/04/disney-plus-kodi-add-on.html and there's no indication of how to use them.
I was having issues with videos launching with German audio which I have now rectified (changed player language setting in Main Kodi settings from "Original lang" to "English") but this highlighted the fact that the settings within the addon have changed from being a list of options within a dialogue (and therefore fairly self-explanatory) to being a blank text entry where you can enter pretty much any text you want. There's absolutely no hint as to what text will work within these fields (default audio / default subtitle) and having tried the obvious ("en", "eng" and "english"), none of them worked.
Even more vague are the next two options: Audio allow list and Subtitle allow list, also text fields with no indication as to what they do or what text will actually work.
As I said, I have now solved my problem using the Kodi settings but It would probably help others if you could either change these options to something tangible that you can select or have a clickable help file detailing what text to enter in these options.

**Comment by matthuisman** [comment] 2021-12-11 00:53
What content played with German audio? Was it German content?
When Kodi is set to Original audio, it should by default select the
language that the content was originally fined in.

**Comment by kevwag** [comment] 2021-12-11 01:18
Yes, that was a little strange actually - it was an American series called "Good Trouble" so you would have thought English was the original language. It wasn't defaulting to the first language in the list either - options 1 & 2 were both German, the first being aac stereo and the second being DD+ 5.1 and it was defaulting to the second one.

**Comment by matthuisman** [comment] 2021-12-16 21:55
i cant reproduce on 19
My kodi player setting is set to "Media default"
All disney+ settings are empty (default settings)
If I play Good Trouble,  english track is marked as [default, original] and is chosen.

I suspect maybe you have set a Default Audio: blah
If blah isnt found, then there will be no default set.
without a default, kodi falls back to the first track I think.

Really, if kodi is set to "Use media default" and no default exists, it should fallback to "original".

I'll see if I can have the code check for "blah" and if not found, then set original to default.

**Comment by matthuisman** [comment] 2021-12-16 23:18
ok, slyguy common 0.48.7 should bring in the desired behaviour of setting original to default if default is not found.
It also now allows multiple defaults. eg Default Audio: de,en   (that will attempt to set to german, then english, then original)

**Closed** 2021-12-18 05:38 UTC

**Comment by refbackshare** [comment] 2024-12-06 09:29
I have the same problem.
Poland
When i try to open Bluey i am getting 
![17334773186885666629717085181887](https://github.com/user-attachments/assets/c4aa95fb-6059-418f-add0-3d8e3b733066)
