### ISSUE TITLE
HBO Max in Spain (maybe all Europe): "Widevine license request failed" when trying to play video

### ISSUE THREAD

**Issue by coder9** [matthuisman/slyguy.addons#709] opened 2024-04-02 21:54 UTC
Hi,

When trying to playing a video (tried True Detective S04E02 and The Tourist S02E03) a "Widevide license request failed" notification pops up. Also TD S04E01 played yesterday, it doesn't today.

My HBO account was set up in Spain and I'm in Spain now. System is OSMC 2024-02-1 (latest version) on Raspberry Pi 4. Tried logging out and back in again in the HBO add-on, re-downloading Widevine CDM library (Linux arm7 - 4.10.2262.3) using Advanced options in HBO settings, and restarting with no success. Up-to-date Android app on phone still works okay.

Relevant log snippet appears to be the following, I deleted the auth parameter because it could be unique to my HBO account:

```
2024-04-02 22:52:43.285 T:559      info <general>: VideoPlayer::OpenFile: plugin://slyguy.hbo.max/?_=play&_play=1&profile_id=[... cut ...]&slug=urn%3Ahbo%3Aepisode%3AGZZF8OwODzrqs
pgEAACB7&_noresume=.pvr
2024-04-02 22:52:43.287 T:1818     info <general>: Creating InputStream
2024-04-02 22:52:43.291 T:1818     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 3840x2160, Adjust refresh rate: 1
2024-04-02 22:52:43.528 T:1818     info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 13, Type: VOD)
2024-04-02 22:52:44.771 T:1821    error <general>: script.module.slyguy - WV License attempt: 1/3 failed: Invalid License Request
2024-04-02 22:52:45.097 T:645      info <general>: JSONRPC Server: Disconnection detected
2024-04-02 22:52:45.370 T:1821    error <general>: script.module.slyguy - WV License attempt: 2/3 failed: Invalid License Request
2024-04-02 22:52:45.975 T:1821    error <general>: script.module.slyguy - WV License attempt: 3/3 failed: Invalid License Request
2024-04-02 22:52:46.486 T:1818    error <general>: CCurlFile::CReadState::FillBuffer - (0xb95b5100) Failed: HTTP returned code 400
2024-04-02 22:52:46.487 T:1818    error <general>: CCurlFile::Open - <http://127.0.0.1:52103/https://drm-emea.api.hbo.com/drm/license/widevine?keygen=playready&drmKeyVersion=2&auth=[... cut ...]> Failed with code 400:
                                                   
2024-04-02 22:52:46.487 T:1818    error <general>: AddOnLog: inputstream.adaptive: License server returned failure
2024-04-02 22:52:47.499 T:1822    error <general>: script.module.slyguy - WV License attempt: 1/3 failed: Invalid License Request
2024-04-02 22:52:48.096 T:1822    error <general>: script.module.slyguy - WV License attempt: 2/3 failed: Invalid License Request
2024-04-02 22:52:48.693 T:1822    error <general>: script.module.slyguy - WV License attempt: 3/3 failed: Invalid License Request
2024-04-02 22:52:49.204 T:1818    error <general>: CCurlFile::CReadState::FillBuffer - (0xb95b5100) Failed: HTTP returned code 400
2024-04-02 22:52:49.205 T:1818    error <general>: CCurlFile::Open - <http://127.0.0.1:52103/https://drm-emea.api.hbo.com/drm/license/widevine?keygen=playready&drmKeyVersion=2&auth=[... cut ...]> Failed with code 400:
                                                   
2024-04-02 22:52:49.205 T:1818    error <general>: AddOnLog: inputstream.adaptive: License server returned failure
2024-04-02 22:52:49.206 T:1818     info <general>: Creating Demuxer
2024-04-02 22:52:49.209 T:1818     info <general>: Opening stream: 1001 source: 256
2024-04-02 22:52:49.322 T:1818     info <general>: [WHITELIST] Searching the whitelist for: width: 960, height: 540, fps: 23.976, 3D: false
2024-04-02 22:52:49.323 T:1818     info <general>: Display resolution ADJUST : 1920x1080 @ 23.976025 Hz (37) (weight: 0.000)
2024-04-02 22:52:49.328 T:559      info <general>: VideoPlayer: OnLostDisplay received
2024-04-02 22:52:49.328 T:559   warning <general>: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2024-04-02 22:52:49.328 T:559   warning <general>: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
2024-04-02 22:52:49.328 T:559      info <general>: GLES: Maximum texture width: 4096
2024-04-02 22:52:49.329 T:1818     info <general>: Creating video codec with codec id: 173
2024-04-02 22:52:49.329 T:1818     info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder HEVC (High Efficiency Video Coding)
2024-04-02 22:52:49.333 T:1818     info <general>: Creating video thread
2024-04-02 22:52:49.333 T:1835     info <general>: running thread: video_thread
2024-04-02 22:52:49.334 T:1818     info <general>: Opening stream: 1003 source: 256
2024-04-02 22:52:49.393 T:1818     info <general>: Finding audio codec for: 86056
2024-04-02 22:52:49.394 T:1818     info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
2024-04-02 22:52:49.394 T:1818     info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2024-04-02 22:52:49.394 T:1818     info <general>: Creating audio thread
2024-04-02 22:52:49.394 T:1839     info <general>: running thread: CVideoPlayerAudio::Process()
2024-04-02 22:52:49.394 T:1818     info <general>: Opening stream: 1011 source: 256
2024-04-02 22:52:49.429 T:1818     info <general>: CDVDSubtitlesLibass: Using libass version 1500000
2024-04-02 22:52:49.429 T:1818     info <general>: CDVDSubtitlesLibass: Creating ASS library structure
2024-04-02 22:52:49.430 T:1818     info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
2024-04-02 22:52:49.430 T:1818     info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
2024-04-02 22:52:49.464 T:1818     info <general>: CDVDSubtitlesLibass: Creating new ASS track
2024-04-02 22:52:50.364 T:559      info <general>: VideoPlayer: OnResetDisplay received
2024-04-02 22:52:50.399 T:1818    error <general>: AddOnLog: inputstream.adaptive: Decrypt Sample returns failure!
2024-04-02 22:52:50.568 T:1818     info <general>: Skipped 101 duplicate messages..
2024-04-02 22:52:50.568 T:1818     info <general>: Process - eof reading from demuxer
2024-04-02 22:52:50.568 T:1818     info <general>: CVideoPlayer::OnExit()
2024-04-02 22:52:50.568 T:1818     info <general>: VideoPlayer: eof, waiting for queues to empty
2024-04-02 22:52:50.569 T:1818     info <general>: Closing stream player 1
2024-04-02 22:52:50.570 T:1818     info <general>: Waiting for audio thread to exit
2024-04-02 22:52:50.580 T:1839     info <general>: thread end: CVideoPlayerAudio::OnExit()
2024-04-02 22:52:50.580 T:1818     info <general>: Closing audio device
2024-04-02 22:52:50.580 T:1818     info <general>: Deleting audio codec
2024-04-02 22:52:50.581 T:1818     info <general>: Closing stream player 2
2024-04-02 22:52:50.584 T:1835     info <general>: thread end: video_thread
2024-04-02 22:52:50.584 T:1818     info <general>: waiting for video thread to exit
2024-04-02 22:52:50.584 T:1818     info <general>: deleting video codec
2024-04-02 22:52:50.585 T:1818     info <general>: Closing stream player 3
2024-04-02 22:52:50.594 T:1802     info <general>: Deleting settings information for files plugin://slyguy.hbo.max/?_=play&_play=1&profile_id=[... cut ...]&slug=urn%3Ahbo%3Aepisode%3AGZZF8OwODzrqspgEAACB7&_noresume=.pvr
2024-04-02 22:52:50.594 T:1818     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2024-04-02 22:52:50.616 T:559      info <general>: CVideoPlayer::CloseFile()
2024-04-02 22:52:50.616 T:559      info <general>: VideoPlayer: waiting for threads to exit
2024-04-02 22:52:50.617 T:559      info <general>: VideoPlayer: finished waiting
2024-04-02 22:52:50.617 T:559      info <general>: CVideoPlayer::CloseFile()
2024-04-02 22:52:50.617 T:559      info <general>: VideoPlayer: waiting for threads to exit
2024-04-02 22:52:50.617 T:559      info <general>: VideoPlayer: finished waiting
2024-04-02 22:52:50.618 T:559      info <general>: GLES: Maximum texture width: 4096
```

I went to the address at 2024-04-02 22:52:46.487 without the http://127.0.0.1:52103/ at the start in Firefox and the text returned is "Method Not Allowed".

If there's anything else I could try or any more info you need please let me know, although I might not be able to immediately answer. Thanks.

**Comment by matthuisman** [comment] 2024-04-02 22:02
maybe caused by https://github.com/matthuisman/slyguy.addons/commit/94492270f7b8fa3e4852b3caeec4c4bd80100ec5

can you try revert slyguy.common 0.77.8 and see if it then works?

**Comment by coder9** [comment] 2024-04-02 22:13
Yep, that fixed it! Thanks!

**Comment by matthuisman** [comment] 2024-04-02 22:31
thanks for testing. ill need to rework that fix :)

**Comment by xdvorakv** [comment] 2024-04-03 05:49
The same issue I see from yesterday on the RPI4. On other platforms it still works. Do you have any hints how to fix it?

**Comment by matthuisman** [comment] 2024-04-03 05:55
Be fixed in about 2 hours

**Comment by coder9** [comment] 2024-04-03 06:00
If your Kodi didn't cache the older version (mine didn't) you can download the zip for the older version from https://slyguy.uk/.repo/repository.slyguy/script.module.slyguy/ then copy it to the Pi and install from zip in the add-ons menu. Also if you have automatic add-on updates then change to notify but don't update.

**Comment by matthuisman** [comment] 2024-04-03 06:42
Just remember to move back to latest else Kodi will pin the old version and
stuff will eventually break

**Comment by matthuisman** [comment] 2024-04-03 08:28
pushed a couple of updates that "should" work.
However, i no longer have access to a HBO Max valid login so unable to test so doing this change blind.

If anyone can help with that, see here:
https://www.matthuisman.nz/2018/06/looking-for-logins.html

(you get a "donor id" in return and an addon that works)

**Comment by coder9** [comment] 2024-04-03 20:55
> pushed a couple of updates that "should" work. However, i no longer have access to a HBO Max valid login so unable to test so doing this change blind.
> 
> If anyone can help with that, see here: https://www.matthuisman.nz/2018/06/looking-for-logins.html

E-mail sent.

**Comment by matthuisman** [comment] 2024-04-03 22:15
thank you :)
Did the fix work?

**Comment by coder9** [comment] 2024-04-03 22:33
Yep, latest HBO Max & latest SlyGuy Common work fine on my set-up. Thanks!

**Comment by Misiukas1966** [comment] 2024-04-03 23:01
![Screenshot_20240403-195051_Kodi](https://github.com/matthuisman/slyguy.addons/assets/32310829/8bc6dc1f-4df1-4d53-a59e-7a71ad745912)

**Comment by matthuisman** [comment] 2024-04-03 23:05
is Brazil on MAX or HBO MAx?

This addon only works for the old HBO MAX (mainly just in europe)

**Closed by matthuisman** 2024-04-03 23:05 UTC

**Comment by Misiukas1966** [comment] 2024-04-03 23:10
Okay, here we are at the maximum.  I'll follow up on the ticket.  looking forward to the new Max app. Thanks

**Comment by Misiukas1966** [comment] 2024-04-03 23:11
*MAX

**Comment by gmjh123** [comment] 2024-04-04 17:54
> pushed a couple of updates that "should" work. However, i no longer have access to a HBO Max valid login so unable to test so doing this change blind.
> 
> If anyone can help with that, see here: https://www.matthuisman.nz/2018/06/looking-for-logins.html
> 
> (you get a "donor id" in return and an addon that works)

Hi Matt. Don't forget I gave you my HBO Max log in a few months ago via email

**Comment by matthuisman** [comment] 2024-04-04 17:59
that was a "MAX" login for USA wasn't it?
I needed a HBO MAX login for Europe :)

**Comment by gmjh123** [comment] 2024-04-04 18:47
Yeah you're right.
