### ISSUE TITLE
Since two Days i have the Issue i can't configure something in the Disney+ addon and the Videos load very long and are stucking and without sound

### ISSUE THREAD

**Issue by xMisterW** [matthuisman/slyguy.addons#827] opened 2024-07-31 21:13 UTC
Since two Days i have the Issue i can't configure something in the addon and the Videos load very long and are stucking and without sound

InputStreamVideo.Adaptive 21.5.0
Device: FireCube TV 3rd Gen
Kodi 22.0 Alpha I
Slyguy Disney+ Addon 0.17.0

Normal Disney+ App on FireTV and in Network a still working

**Comment by matthuisman** [comment] 2024-08-01 01:30
can you please provide a full kodi debug log showing the error / playback fail

**Comment by matthuisman** [comment] 2024-08-01 04:11
also, try going back to older inputstream.adaptive.
21.5.0 is brand new and may have issues
try go back to v21.4.10

**Comment by matthuisman** [comment] 2024-08-01 04:12
i also dont have a disney+ login currently so unable to test / debug
If you can help with that, see here: https://www.matthuisman.nz/2018/06/looking-for-logins.html

**Comment by xMisterW** [comment] 2024-08-01 07:11
With the Full Debug Log i have to look. But after Reasearch i've done last night i think the Issue is inputsream.adaptive 2.1.5.0.

But to use an older release i have to build kodi on my own, and for that i have look for an cli/terminal tool to use on fireTV.

I would first go and try 21.4.10 or 21.4.8 and if that doesnt work 21.4.1

**Comment by matthuisman** [comment] 2024-08-01 08:06
why do you need to build your own? just download the older android version of inputstream adaptive and install via zip

**Comment by xMisterW** [comment] 2024-08-01 08:23
I only find this page https://github.com/xbmc/inputstream.adaptive/releases with the Source code as Zip and this gives an Error if i want to install it.

**Comment by xMisterW** [comment] 2024-08-01 08:29
Nice. Thank you very much. At the Moment i am at work. In the Evening i am at home and can try it with that. I will give an update if it can be closed.

How can i support here: https://www.matthuisman.nz/2018/06/looking-for-logins.html

i only have a share on accounts. Only i can provide is apple tv

**Comment by matthuisman** [comment] 2024-08-01 08:30
its ok, i should be able to find someone who can let me use their disney+ :)

**Comment by CastagnaIT** [comment] 2024-08-01 08:57
@xMisterW to notice that you are using ISA 21.5.0 on Kodi 22
this can lead to side effects problems due to different kodi core build

please update with these test build for Kodi 22:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/22.1.0-Piers/3/artifacts

after reboot the device before try to play a video, and let we know

**Comment by xMisterW** [comment] 2024-08-01 09:02
@CastagnaIT Ok. Your Netflix Addon was working with 21.5.0 on Kodi 22 besides some error messages

**Comment by xMisterW** [comment] 2024-08-01 16:56
Kodi 22 newest version plus isa 22.10 is not working properly. Now i'm going to test kodi 21 + isa 21.4.10

**Comment by xMisterW** [comment] 2024-08-01 17:26
Kodi 21 + ISA 21.4.10 not working too i will try 21.4.8

**Comment by matthuisman** [comment] 2024-08-01 18:46
Provide full Kodi debug log

**Comment by matthuisman** [comment] 2024-08-01 22:10
there could be another issue your hitting if Inpustream Adaptive is set to "adaptive switching"
(https://github.com/matthuisman/slyguy.addons/issues/765#issuecomment-2170889101)

That was fixed in 21.5.0 but that new version may have now broken 5.1 sound.

So please do
1) set inputstream adaptive stream selection mode to "manual"
2) Try 21 + ISA 21.4.10

If doesnt work - provide full kodi debug log

**Comment by matthuisman** [comment] 2024-08-02 08:21
confirmed there is a bug in IA with 21.5.0
as per here: https://github.com/xbmc/inputstream.adaptive/issues/1617

Work around for now is to 

1) downgrade IA to 21.4.10
or 
2) set plugin -> settings -> Player -> Codecs -> Max Audio channels to 2

**Comment by xMisterW** [comment] 2024-08-02 08:26
Oh ok so i have to choose max audio channels 2 on the first run with the settings of the Addon?
I don't know in the moment how to get the logs i haven't done that so far.
So the Way to go is 22 with 22.10 or 21 with 21.5.0 with only two audio channels at the moment?

**Comment by xMisterW** [comment] 2024-08-02 10:59
Nothing of that Works anymore i installed different combinations a hundred Times now. and nothing is working.
How can i make a full debug log

**Comment by CastagnaIT** [comment] 2024-08-02 11:02
tests for k21 https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1620/1/artifacts
tests for k22 https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1618/3/artifacts

**Comment by xMisterW** [comment] 2024-08-02 11:35
tests for k22 https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1618/3/artifacts


That ist working with Inputstream adaptive on adaptive and with Dolby Atmos
On KODi 22 mavensbuild for android

**Comment by CastagnaIT** [comment] 2024-08-02 11:55
I don't waste time with unofficial builds

**Comment by xMisterW** [comment] 2024-08-02 12:22
Ok then i will test the latest development Build from Kodi v22 from kodi.tv for a more validation

**Comment by xMisterW** [comment] 2024-08-02 13:49
This one <html>

kodi-20240729-80f4ac87-master-armeabi-v7a.apk

plays slyguy disney,paramount and sandmann79 Amazon VOD properly (Adaptive Setting + Dolby Digital Multi Channel) with https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1618/3/artifacts

But the Addon of @CastagnaIT  is not working it loads very long the videos like on the other addons when inputstream adaptive was broken.

This is the way i will go till everything is fixed 3 addons i use will work this way

**Comment by matthuisman** [comment] 2024-08-02 21:44
@xMisterW your issue keeps changing. Its now just a Netflix addon issue?

So it sounds like your original issue with my add-ons is fixed with 
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1618/3/artifacts

Therefore, Im closing this issue.
Please open an issue on Netflix repo for that issue :)

**Closed by matthuisman** 2024-08-02 21:44 UTC
