### ISSUE TITLE
ESPN addon - ESPN3 stops/starts/tries to change resolution constantly while in commercials and after

### ISSUE THREAD

**Issue by lionsnob** [matthuisman/slyguy.addons#46] opened 2021-08-04 02:01 UTC
Hi Matt -

Please see attached log from Windows. The issue is really noticeable on a Shield but I've never uploaded a log from one.

I've seen this issue only with ESPN3 so far, where the video of the event is 720p but commercials can be any resolution/rate. When going into the commercial break the stuttering starts and when exiting the system can't recover. My whitelist is turned on with various 4k and 1080p resolutions selected.

Thank you!

[kodi.log](https://github.com/matthuisman/slyguy.addons/files/6928032/kodi.log)

**Comment by lionsnob** [comment] 2021-08-04 02:06
It appears if I turn “Adjust display refresh rate” to “off” this issue doesn’t appear, but I’d rather leave it on.

**Comment by matthuisman** [comment] 2021-08-04 02:08
that will be out of my hands unfortunately.
either a kodi or inputstream adaptive issue

**Comment by lionsnob** [comment] 2021-08-04 02:09
Ok, thanks Matt.

**Comment by matthuisman** [comment] 2021-08-04 02:11
basically every ad has to be treated as a new stream in kodi so it does actually adjust to the ads resolution.
And it seems that triggers kodi to try to change refresh rate to match.

I guess the solution is Kodi always "sticks" to the same refresh rate at start of playback and doesn't try to change

**Comment by matthuisman** [comment] 2021-08-04 02:14
does it work if you change refresh rate to On start/stop?
I assumed that would only try to change the rate once?

**Comment by lionsnob** [comment] 2021-08-04 02:22
Hi Matt -
No, it was much worse using that setting on the Shield for whatever reason.

Steve

**Comment by matthuisman** [comment] 2021-08-04 02:23
the issue is that the refresh rate keeps changing right?

**Comment by lionsnob** [comment] 2021-08-04 02:25
Hi Matt -
Yes. The system can’t “decide” or settle on a refresh rate.

Steve

**Comment by matthuisman** [comment] 2021-12-06 21:49
@lionsnob @kyl416
just pushed update to Slyguy common that will remove frame-rate from any manifests.
This may help solve this issue.
Can you report back here?

**Comment by lionsnob** [comment] 2021-12-08 01:58
Hello -

The issue is not solved. It occurs on ESPN3 still. I can’t get a log tonight but can get one tomorrow if helpful.

Steve

**Comment by lionsnob** [comment] 2021-12-08 02:02
See attached video.

**Comment by matthuisman** [comment] 2022-05-14 07:42
https://github.com/xbmc/xbmc/pull/21372
May be what we have been waiting for

**Comment by lionsnob** [comment] 2022-05-14 12:14
Excellent!

Steve

**Comment by matthuisman** [comment] 2022-05-14 19:32
Did you try?

**Comment by lionsnob** [comment] 2022-05-14 19:55
I did not think to. Will do so on my PC sometime this week assuming a computer monitor can handle those resolutions and refresh rate.

Steve

**Comment by matthuisman** [comment] 2022-05-14 20:03
Trying on lower res should be fine. And you'll need to use the latest
nightly build of Kodi 20

**Comment by lionsnob** [comment] 2022-05-31 01:29
Kodi 20 nightly on Ubuntu 22.04 only lets me select 1920x1080p 60Hz as a resolution. Will try and find another solution.

**Comment by matthuisman** [comment] 2022-07-01 12:21
Fixed in Kodi 20 so closing :)

**Closed by matthuisman** 2022-07-01 12:21 UTC
