### ISSUE TITLE
[Paramount+] Live sport streams fail to play (expaterror)

### ISSUE THREAD

**Issue by puppinoo** [matthuisman/slyguy.addons#542] opened 2023-08-19 15:58 UTC
Hi, and thanks for these amazing addons.
I'm having this exception only with Serie A links:

xml.parsers.expat.ExpatError: no element found: line 1, column 0

File "expatbuilder.py", line 223, in parseString
                   <....>

Also I opened another issue last year which I negletted (sorry about that but championship was over) about the name of the Serie A events. Not sure I can reopen it but basically all the Italian soccer matches are not named correctly but they all are named "Serie A".

Thanks.
Pino.

**Comment by jokla** [comment] 2023-08-19 17:03
Hi! 
I get the same error. Paramount+ (0.6.7/0.71.0).

**Comment by Merendino1234** [comment] 2023-08-19 17:11
Getting the same error on all devices
Using US account from Italy with US VPN (SFSHARK)
Tried on android omega preview; nexus 20.2 and on windows with omega preview and 19.4

if it helps I can send logs

**Comment by puppinoo** [comment] 2023-08-19 17:11
> Hi! I get the same error. Paramount+ (0.6.7/0.71.0).

Are you using Vpn / smartdns service too? (I'm in italy and using smartdns service towards US).

**Comment by Merendino1234** [comment] 2023-08-19 17:22
> > Hi! I get the same error. Paramount+ (0.6.7/0.71.0).
> 
> Are you using Vpn / smartdns service too? (I'm in italy and using smartdns service towards US).
> 
> p.s.: wow, fast replies :)

hi, you can log in on the website or the mobile app? Because i can only on kodi. I think it's the vpn fault

**Comment by puppinoo** [comment] 2023-08-19 17:37
> > > Hi! I get the same error. Paramount+ (0.6.7/0.71.0).
> > 
> > 
> > Are you using Vpn / smartdns service too? (I'm in italy and using smartdns service towards US).
> > p.s.: wow, fast replies :)
> 
> hi, you can log in on the website or the mobile app? Because i can only on kodi. I think it's the vpn fault

Yes, I can. In fact Official P+ app on my Fire Tv stick AND chrome on my ubuntu pc are working correctly.

**Comment by puppinoo** [comment] 2023-08-19 17:39
BUT
I tried SurkShark in past caus price was appealing but it never worked with P+. So I went back to SmartDns (NordVPN works fine too).
Of course it could not be your case but I wanted to say this.,

**Comment by jokla** [comment] 2023-08-20 11:09
> > Hi! I get the same error. Paramount+ (0.6.7/0.71.0).
> 
> Are you using Vpn / smartdns service too? (I'm in italy and using smartdns service towards US).
> 
> p.s.: wow, fast replies :)

Yes, and the streaming is working fine on my browser un Ubuntu. On the Kodi app, everything seems working except for the Seria A matches.

**Comment by puppinoo** [comment] 2023-08-20 12:06
Probably off topic here but I Just noticed that on official P+ app (sideloaded  US version) the events into "Matches replays" section stopped working with a msg "not available. Try later". Pretty sure they worked last year.
Wondering of its a vpn/DNS domani issue or P+ service issue.

**Comment by puppinoo** [comment] 2023-08-22 12:44
> Hi all, same error on saturday trying to watch Serie A match but this is not a SerieA problem. Checking for others live channels, some of them were working, some others not (Paw Patrol, Preschool, Star Trek). I'm using NordVPN and from the Android app on the phone I was able to see the match without problem. I actually have the problem.

I just tested a few other channels like 80/90 Sitcoms and 24/7 Laughs. They look to be working but once opened they are broken. Playback jumps back and forth. I dont watch them often but It was just to report.

**Comment by marcozzino80** [comment] 2023-08-27 16:18
Serie A live match instead still not working. 
xml.parser.expat.ExpatError: no element found: line 1, column 0
Could I help to resolve this issue?

Thank you,
Marco.

**Comment by Kirylo** [comment] 2023-08-27 16:43
Hello All,

same issue here, the error is only happening with live Football all other live streams seem to be working normally. I am using NORD VPN. I can watch the football live stream only from the browser and not from the add on.

![image](https://github.com/matthuisman/slyguy.addons/assets/20689503/622d6ace-89d2-46e4-af80-324e6471cee6)

**Comment by puppinoo** [comment] 2023-08-27 17:02
I guess there Is not much we can do. 
Not expert but I think that addon just retrieves a videoid and then sends It to a remote proxy (in unprotected http, not sure if this is relevant) which in Serie A cases replies with 404 (link not found). So until reply Is not fixed if you can use  a Fire TV Stick or any other Android TV device you can sideload the Usa apk which Is working fine here
https://apkcombo.com/paramount-plus/com.cbs.ott/download/apk

**Comment by matthuisman** [comment] 2023-08-29 08:03
i cant reproduce the issue...

Im trying series A match replays and they are OK...

Is this error only with live matches?

**Comment by jokla** [comment] 2023-08-29 08:07
@ma

> i cant reproduce the issue...
> 
> Im trying series A match replays and they are OK...
> 
> Is this error only with live matches?

Hi @matthuisman,
Yes, I get the error only on live matches. The replays are working :+1:

**Comment by marcozzino80** [comment] 2023-08-29 08:33
i sent mine.
next serieA match is on friday 1th september at 18.30 CEST (Sassuolo - Hellas Verona)

Thank you!

**Comment by matthuisman** [comment] 2023-08-29 09:51
thanks @marcozzino80 !

NZ times for matches for my reference
![image](https://github.com/matthuisman/slyguy.addons/assets/6225961/67b13d20-509d-49cc-bdca-d4b9f41e133d)

**Comment by marcozzino80** [comment] 2023-08-29 11:08
Thank to you.
I think you can try also with live matches of UEFA Champions League (scheduled for this eventing in Italy). I don't know if they throw the same error or is only a SerieA problem. This evening i'll check.
if it's a problem of all live matches maybe you'll find some more suitable for your timezone.

**Comment by puppinoo** [comment] 2023-08-29 18:44
I confirm it's happenong right now.
Same exception.

**Comment by puppinoo** [comment] 2023-08-29 20:38
Just downloaded latest update and It looks like It fixed (at least UEFA. Will have tò check Serie A on Saturday). You also fixed the names.

Thanks for Amazing work.
Cheers.

**Comment by ashtoncain** [comment] 2023-08-29 21:05
Working for me also now :) Able to watch the UEFA section.

Thank you for your work !!

**Comment by puppinoo** [comment] 2023-08-29 21:05
Before this issue is closed since It's full of non americans with P+ and until late September P+ offers a 50% discount coupon (coupon Is: "sports") but It cant be bought with gift cards and my virtual card stopped working, does anyone know a payment method still working to use discount codes?
Thanks and Sorry for another off topic.
Cheers.

**Comment by matthuisman** [comment] 2023-08-29 21:19
fixed with [slyguy.paramount.plus -> v0.7.0](https://github.com/matthuisman/slyguy.addons/commit/6a6ce79a0a27affbf81df892e0696eaf97523317)

**Comment by matthuisman** [comment] 2023-08-30 20:45
oh bummer.
https://github.com/matthuisman/slyguy.addons/blob/master/slyguy.paramount.plus/resources/lib/api.py#L367
could you add print(session) above that line and get me the output?

**Comment by marcozzino80** [comment] 2023-08-30 21:30
ok sure.. but actually live are terminated. I'll try with the next.
print command should show something on the screen?
anyway trying on kodi on my pc on windows it works. the problem is only on htpc with libreelec.

**Comment by matthuisman** [comment] 2023-08-30 21:41
print should show in the log i think :)

**Comment by marcozzino80** [comment] 2023-08-30 22:01
in the meantime trying with other live channel i get error on row 403. Added this line 
        raise APIError("{}".format(session))
before and i get this msg
{'Error Message': 'IP: 185.199.102.160 is inside VPN', 'message': 'IP: 185.199.102.160 is inside VPN', 'success': False, 'isInVPN':True}

**Comment by marcozzino80** [comment] 2023-08-30 22:28
tested with 2 channels: kodi on windows (with nordvpn installed) works correctly; kodi on libreelec (using VPN Manager for OpenVPN with nordvpn credentials) i get error message "is Inside VPN". Could be a VPN problem? they are able to see that i am in VPN?

**Comment by matthuisman** [comment] 2023-08-30 23:44
oh great. so i think the new code is fine then.
Ill just add a check for that VPN stuff to session and give a better errror

**Comment by matthuisman** [comment] 2023-08-31 04:51
latest version adds a check and better error for that error from session :)

**Closed by matthuisman** 2023-08-31 04:51 UTC
