### ISSUE TITLE
[HBO Max] No movie descriptions in the lists

### ISSUE THREAD

**Issue by jsalik** [matthuisman/slyguy.addons#171] opened 2022-04-08 21:44 UTC
When browsing lists there are only titles, it would be great to have them especially when using list in widget

**Comment by matthuisman** [comment] 2022-04-08 21:47
Please check closed issues

**Comment by matthuisman** [comment] 2022-04-08 22:26
HBO doesnt actually return this data as they have no need for it on their apps or website.
Only way known currently is to request the data for every movie = a lot of requests = slow loading of lists.

There might be an api endpoint where you can request multiple items data - but nothing I know of yet.

**Comment by jsalik** [comment] 2022-04-09 17:17
Thanks, yep requests for each item would be total overkill, maybe with some good caching mechanism, but still, not a best idea, maybe they will add descriptions in the future. 
The awesome future would be integration with Kodi scraper, that would solve descriptions problem and we could download extra artwork. Don't know if this is possible though.

**Comment by matthuisman** [comment] 2023-01-15 10:21
closing as duplicate of https://github.com/matthuisman/slyguy.addons/issues/181

**Closed by matthuisman** 2023-01-15 10:21 UTC
