### ISSUE TITLE
Stremium channels buffers then replays

### ISSUE THREAD

**Issue by MajinLugia** [matthuisman/slyguy.addons#836] opened 2024-08-07 01:02 UTC
spawned from original issue: https://github.com/matthuisman/slyguy.addons/issues/831

Stremium channels (more specifically Sling channels) are buffering when the programming ends then the programming that ended will replay when the buffer ends while using slyguy common linked [here](https://github.com/user-attachments/files/16516592/script.module.slyguy.zip).
I am also testing for issues on Kodi 20.5 and the only issue on there is that the streams are about 20-30 seconds behind without buffering at the end of programming.

**Comment by matthuisman** [comment] 2024-08-11 01:24
sounds like this is an inputstream adaptive issue then with newer IA

**Comment by MajinLugia** [comment] 2024-08-11 22:42
Hmmm any clue why the issue persists even when downgrading inputstream adaptive?
Should I attach a debug log?

**Comment by matthuisman** [comment] 2024-08-11 22:46
stremium is widevine so you can disable inpustream.
And you cant downgrade to the same IA version that Kodi 20 uses. 
And they dont keep many old versions so hard to go back further.

Or is this a new issue recently on Kodi 21?
Or has 21 never worked correctly?

**Comment by MajinLugia** [comment] 2024-08-11 22:52
This issue is recent on Kodi 21. It was the most stable setup ever until something broke about 2 weeks ago unfortunately.

**Comment by matthuisman** [comment] 2024-08-11 22:56
so, with 21.4.10 - try disabling slyguy proxy in stremium addon settings and see if has same issue

**Comment by MajinLugia** [comment] 2024-08-12 00:39
I disabled slyguy proxy on both 21.4.10 and latest version and I am having no issues! With that being sad, what side effects are present with the proxy being disabled?

**Comment by matthuisman** [comment] 2024-08-12 02:08
we will want proxy :) so ill need figure out what changes thats doing that causes it
Can you please try with 21.5.1 with proxy off and confirm OK

**Comment by MajinLugia** [comment] 2024-08-12 02:22
Yes, I tested with 21.5.1 with proxy off and the buffer isn’t present.

**Comment by matthuisman** [comment] 2024-08-12 02:25
ok sweet. What slyguy common ver are you using when testing currently?

**Comment by MajinLugia** [comment] 2024-08-12 02:28
I’m using 0.84.64 of slyguy common!

**Comment by matthuisman** [comment] 2024-08-12 02:30
and the problem persisted even with https://github.com/user-attachments/files/16516592/script.module.slyguy.zip ? (version 99.99.99)

**Comment by MajinLugia** [comment] 2024-08-12 02:34
Yes that is correct, the problem went away after turning off slyguy proxy!

**Comment by matthuisman** [comment] 2024-08-12 02:37
Ok, lets try:

99.99.90
Remove dynamic mpd changes
(still has manifest parse every refresh)
[script.module.slyguy-90.zip](https://github.com/user-attachments/files/16576930/script.module.slyguy-90.zip)

**Comment by MajinLugia** [comment] 2024-08-12 11:10
Okay so I was testing it out and it seems okay with some channels but I noticed that the Disney Junior channel doesn’t play now which is a channel I used to do testing due to odd and short programming times. I need to conduct some more testing with the rest of the channels and see if they have this problem.

**Comment by matthuisman** [comment] 2024-08-13 09:16
ok thanks. let me know

**Comment by MajinLugia** [comment] 2024-08-13 23:20
So far it seem like everything works but this is unrelated to stremium but Paramount+ is saying its unavailable in my region now, I’m not using a vpn or any fancy setup.

**Comment by matthuisman** [comment] 2024-08-14 02:56
please keep on topic. there is another issue about paramount

**Comment by matthuisman** [comment] 2024-08-14 08:04
so, seems 99.99.90 was OK

Can you please try this 99.99.91
[script.module.slyguy.zip](https://github.com/user-attachments/files/16609483/script.module.slyguy.zip)

**Comment by MajinLugia** [comment] 2024-08-15 21:44
Yeah 99.99.91 bought back the buffering and restarting issue. 99.99.90 worked great.

**Comment by matthuisman** [comment] 2024-08-15 22:10
ok, we down to 2x possible chunks of code that could cause :)
This last test will tell us

I suspect this WILL work (99.99.92)
[script.module.slyguy.zip](https://github.com/user-attachments/files/16630760/script.module.slyguy.zip)

**Comment by MajinLugia** [comment] 2024-08-16 00:12
Stremium channels are working fine on 99.99.92!

**Comment by matthuisman** [comment] 2024-08-16 02:30
thanks. would you have a kodi log on one of the occassions where it buffers?

**Comment by matthuisman** [comment] 2024-08-16 02:33
if not, then could you please test with 99.99.93
[script.module.slyguy-99.99.93.zip](https://github.com/user-attachments/files/16632215/script.module.slyguy-99.99.93.zip)
This is re-enabling the code but putting it in try/except
Trying to figure out if the issue is

1) the change manifest is causing inputstream adaptive to have isues
or
2) it cant make the change when the manifest changes at the end of program, raising an error and causing kodi to stall / buffer

**Comment by MajinLugia** [comment] 2024-08-17 14:45
How do I properly turn on debugging and where would the logs be located?
Also, I’m testing 99.99.93 and its doing the buffering and replay thingy again and its also behind like 20 seconds as I had it playing side by side with the standard stremium app.

**Comment by matthuisman** [comment] 2024-08-19 07:30
ok. if thats still causing the issue then its not erroring :) ill try push a slyguy update to fix

**Comment by matthuisman** [comment] 2024-08-19 08:27
[script.module.slyguy -> v0.85.7](https://github.com/matthuisman/slyguy.addons/commit/29c487bff71f30c77d3e473be5822a8d8b19781e) removes the troublesome code.

You should now be able to update to this one (may need to manually select it from repo) and your issue should be fixed

**Closed by matthuisman** 2024-08-19 08:27 UTC
