### ISSUE TITLE
Streamotion (kayo,binge,flash) token Geo Blocked error

### ISSUE THREAD

**Issue by scottydulton** [matthuisman/slyguy.addons#398] opened 2023-02-16 03:36 UTC
Hey Matt, 
Kayo is giving the same geo error as yesterday

**Comment by matthuisman** [comment] 2023-02-16 09:37
fixed now with latest slyuy common

**Comment by scottydulton** [comment] 2023-02-17 02:19
Hey Matt same error again this morning

**Comment by matthuisman** [comment] 2023-02-17 03:16
https://forums.whirlpool.net.au/thread/3p6vxxp3?p=125#r2490

**Comment by undecomposed** [comment] 2023-02-17 03:56
Matt, do you mind elaborating what the issue is? Is it the DRM or something else?

**Comment by matthuisman** [comment] 2023-02-17 04:08
It's not drm related. I don't want to go into detail sorry. Ill try fix
again tonight

**Comment by undecomposed** [comment] 2023-02-17 15:46
@matthuisman don't know if you did anything  but Flash seems to work for me now.

**Comment by Carty89** [comment] 2023-02-17 20:40
Gday mate thanks for your reply.

yeah not to sure what’s going on was working last weekend but just kept coming up with that same geo error past 2 days. I initially thought it was my modem but kayo was working as per normal on all devices just not working through Kodi it was really bazar.

il try again this morning mate and will keep you posted.

cheers again mate

**Comment by matthuisman** [comment] 2023-02-23 10:52
Looks like 64bit Linux Kodi 18.9 (LibreELEC 9.2.6)
still having issues:
https://paste.kodi.tv/etikemuzuz.kodi

**Comment by scottydulton** [comment] 2023-03-08 08:24
@matthuisman this issue has arisen again

**Comment by scottydulton** [comment] 2023-03-14 01:05
@matthuisman geo error occuring again :(

**Comment by matthuisman** [comment] 2023-03-14 01:09
:( pain in my a$$

**Closed** 2023-03-23 10:47 UTC
