### ISSUE TITLE
script.module.slyguy crashes Linux platforms

### ISSUE THREAD

**Issue by cgcgcgcgcg** [matthuisman/slyguy.addons#56] opened 2021-08-20 22:40 UTC
It's a known bug I've dealt with before, this time is _abnf.py in addons/script.module.slyguy/resources/modules/websocket/ that seems to be taken from an old version of script.module.websocket (the dev fixed it after I pinpointed it).
If you replace line 34 in _abnf.py with:
numpy = None
script.module.slyguy stops crashing Linux.

More info:
https://github.com/xbmc/xbmc/issues/19324#issuecomment-842019792

**Comment by matthuisman** [comment] 2021-08-20 23:11
great work finding the cause
just pushed the fix to slyguy common: https://github.com/matthuisman/slyguy.addons/commit/e252bca4f7d4e42614cc8386adc2c1be81f1fb89

**Closed by matthuisman** 2021-08-20 23:11 UTC

**Comment by cgcgcgcgcg** [comment] 2021-08-20 23:19
Thank you for the fast fix.
