### ISSUE TITLE
DisneyPlus no Audio

### ISSUE THREAD

**Issue by maddavo** [matthuisman/slyguy.addons#97] opened 2021-12-07 10:19 UTC
I seem to have lost audio in the DisneyPlus Addon in the last week.

Pi4
LibreELEC 9.2.8
Kodi 18.9
Disney+ 10.6
SlyGuy Repository 0.0.2

Last verified working approx 29th November.  First time audio gone 7th December.
Something broke or something else I should check?

**Comment by mmarodin** [comment] 2021-12-07 13:05
Me too :(

I think that with the last update of Slyguy Common interface the audio language filtering in Disney+ with Kodi 18 has not been working yet.
Contents has audio if I remove the audio filtering , but not in my language!

Could you please fix it?
Thanks, bye

**Comment by matthuisman** [comment] 2021-12-07 17:00
What is your audio language settings set to? The whitelist and default?

**Comment by mmarodin** [comment] 2021-12-07 17:34
Hi.

I have just tried also the solution to #92, without success. It has not been caused by the level of widevine.

Default audio is _it_ (Italian).
Whitelist is _en,es,it_.

I tested also only with _en_, but the issue persists.
The issue disappears only is I remove the whitelist, but not all titles could be in Italian in this way with Kodi 18.x.

Thanks

**Comment by matthuisman** [comment] 2021-12-07 20:18
fixed with latest slyguy common 0.48.2

**Closed by matthuisman** 2021-12-07 20:18 UTC
