### ISSUE TITLE
Can't access sports in foxtel go

### ISSUE THREAD

**Issue by liam8888999** [matthuisman/slyguy.addons#421] opened 2023-03-14 17:43 UTC
Getting json parse error when trying to access the sports section in foxtel go. It works in the app

**Comment by matthuisman** [comment] 2023-03-15 01:24
ive had another report of this but I couldn't reproduce.
Maybe its a rollout thing and i'll get the same soon enough

**Comment by liam8888999** [comment] 2023-03-15 05:06
If you have email or something I can send you my password to test if that will help at all On 15 Mar 2023, at 12:24 pm, Matt Huisman ***@***.***> wrote:﻿
ive had another report of this but I couldn't reproduce.
Maybe its a rollout thing and i'll get the same soon enough

**Comment by liam8888999** [comment] 2023-03-15 05:11
Or more logs if you need

**Comment by matthuisman** [comment] 2023-03-15 07:23
just tried and still working for me.
maybe set your password to something random and email me it then you can change it back after

**Comment by liam8888999** [comment] 2023-03-15 10:58
sent an email

**Comment by matthuisman** [comment] 2023-03-16 11:01
thanks @liam8888999 

should be fixed in  [v0.9.5](https://github.com/matthuisman/slyguy.addons/commit/4ff8777fd390d25801b58cf8c00260f1186e7c7f)

**Closed** 2023-03-16 11:01 UTC
